FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-performance.jar /home/lest/lest-performance.jar

ENTRYPOINT ["java", "-jar", "lest-performance.jar"]
