FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-ai.jar /home/lest/lest-ai.jar

ENTRYPOINT ["java", "-jar", "lest-ai.jar"]
