FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-plugin.jar /home/lest/lest-plugin.jar

ENTRYPOINT ["java", "-jar", "lest-plugin.jar"]
