FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-task.jar /home/lest/lest-task.jar

ENTRYPOINT ["java", "-jar", "lest-task.jar"]
