sonar.projectKey=lest-work_lest
sonar.organization=lest-work

# Maven auto-config (provided by sonar-maven3-plugin)
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8

# Coverage
sonar.coverage.jacoco.xmlReportsPaths=target/site/jacoco/jacoco.xml

# Exclude generated/unnecessary files
sonar.exclusions=**/target/**,**/*.class,**/target/**,**/resources/application*.yml,**/resources/bootstrap.yml

# Test exclusions
sonar.test.inclusions=**/*Test.java,**/*Tests.java
sonar.coverage.exclusions=**/*Test.java,**/*Tests.java
