FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-notification.jar /home/lest/lest-notification.jar

ENTRYPOINT ["java", "-jar", "lest-notification.jar"]
