FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-auth.jar /home/lest/lest-auth.jar

ENTRYPOINT ["java", "-jar", "lest-auth.jar"]
