FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-release.jar /home/lest/lest-release.jar

ENTRYPOINT ["java", "-jar", "lest-release.jar"]
