FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-monitor.jar /home/lest/lest-monitor.jar

ENTRYPOINT ["java", "-jar", "lest-monitor.jar"]
