FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-project.jar /home/lest/lest-project.jar

ENTRYPOINT ["java", "-jar", "lest-project.jar"]
