# 基础镜像
FROM  openjdk:17
# author
MAINTAINER lest

# 挂载目录
VOLUME /home/lest
# 创建目录
RUN mkdir -p /home/lest
# 指定路径
WORKDIR /home/lest
# 复制jar文件到路径
COPY ./jar/lest-modules-project.jar /home/lest/lest-modules-project.jar
# 启动服务
ENTRYPOINT ["java","-jar","lest-modules-project.jar"]
