FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-meeting.jar /home/lest/lest-meeting.jar

ENTRYPOINT ["java", "-jar", "lest-meeting.jar"]
