FROM eclipse-temurin:21-jre-alpine
LABEL maintainer="lest"

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY jar/lest-gateway.jar /home/lest/lest-gateway.jar

ENTRYPOINT ["java", "-jar", "lest-gateway.jar"]
