FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-system.jar /home/lest/lest-system.jar

ENTRYPOINT ["java", "-jar", "lest-system.jar"]
