# 基础镜像
FROM eclipse-temurin:25-jre-noble
# author
MAINTAINER lest

# 挂载目录
VOLUME /home/lest
# 创建目录
RUN mkdir -p /home/lest
# 指定路径
WORKDIR /home/lest
# 复制jar文件到路径
COPY ./jar/lest-modules-system.jar /home/lest/lest-modules-system.jar
# 启动服务
ENTRYPOINT ["java","-jar","lest-modules-system.jar"]
