FROM eclipse-temurin:21-jre-alpine
MAINTAINER lest

VOLUME /home/lest
RUN mkdir -p /home/lest

WORKDIR /home/lest
COPY ./jar/lest-file.jar /home/lest/lest-file.jar

ENTRYPOINT ["java", "-jar", "lest-file.jar"]
