import { mockProjectWorkspaceService } from "./mock";
export { mockProjectWorkspaceService } from "./mock";
export type { ProjectWorkspaceService } from "./service";
export type {
  BoardColumn,
  BoardColumnSettingsRequest,
  BoardColumnSettingsResponse,
  BoardIssueCard,
  BoardIssueDetailRequest,
  BoardIssueDetailResponse,
  BoardRequest,
  BoardResponse,
  BoardSprint,
  BoardSprintsRequest,
  BoardSprintsResponse,
  BoardWipWarning,
  CloseSprintRequest,
  CloseSprintResponse,
  ComponentFeedbackStates,
  ComponentGalleryRequest,
  ComponentGalleryResponse,
  CreateSprintRequest,
  CreateSprintResponse,
  DangerActionSpec,
  ExportReportRequest,
  ExportReportResponse,
  MoveBoardIssueRequest,
  MoveBoardIssueResponse,
  ProjectSettingsRequest,
  ProjectSettingsResponse,
  ReportConfigRequest,
  ReportConfigResponse,
  ReportDrilldownRequest,
  ReportDrilldownResponse,
  ReportFilterOptionsRequest,
  ReportFilterOptionsResponse,
  ReportFilterState,
  ReportsRequest,
  ReportsResponse,
  RoadmapRequest,
  RoadmapResponse,
  SaveReportConfigRequest,
  SaveReportConfigResponse,
  SprintCheckItem,
  SprintClosePreviewRequest,
  SprintClosePreviewResponse,
  SprintStartPreviewRequest,
  SprintStartPreviewResponse,
  StartSprintRequest,
  StartSprintResponse,
  UpdateBoardColumnSettingsRequest,
  UpdateBoardColumnSettingsResponse,
  WorkspaceNotification,
  WorkspaceNotificationsRequest,
  WorkspaceNotificationsResponse,
  WorkspaceRequest,
  WorkspaceSearchRequest,
  WorkspaceSearchResponse,
  WorkspaceShellRequest,
  WorkspaceShellResponse,
  WorkspaceUser,
  ReportSavedFilter,
} from "./contracts";

/** Default service implementation (currently mock) */
export const projectWorkspaceService = mockProjectWorkspaceService;
